version: 2
jobs:
  build:
    machine: true
    working_directory: /go/src/github.com/CircleCI-Public/consul-envoy-xds
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - restore_cache:
          keys:
          - vendor-pkg-{{ checksum "Gopkg.lock" }}
          - vendor-pkg-
      - run:
          name: Install Dependencies
          command: |
            make setup
      - save_cache:
          paths:
            - ./vendor
            - "/go/pkg"
          key: vendor-pkg-{{ checksum "Gopkg.lock" }}
      - run:
          name: Run tests
          command: |
            make test
      - run:
          name: Docker Build
          command: |
            TAG=0.1.0-$CIRCLE_SHA1
            docker build -t gojektech/consul-envoy-xds:$TAG .
      - run:
          name: Docker Publish
          command: |
            TAG=0.1.0-$CIRCLE_SHA1
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push gojektech/consul-envoy-xds:$TAG
